backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/BenchmarkWriteAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/storage/db/DatabaseStorage.java

In rare circumstances where velcom crashes right after it inserted a run into the database, but before it inserted any of the measurements and measurement values, an inconsistent state in the database was possible.
To prevent this, runs are now inserted along with their respective measurements and measurement values using a transaction.
In addition, a new method DatabaseStorage#acquireTransaction() is introduced to allow an easier and safer interaction with transactions.

Nest run inserts into a transaction

---

frontend/.editorconfig
frontend/package.json
frontend/src/components/dialogs/DatapointDialog.vue
frontend/src/components/graphs/Dygraph-Detail.vue
frontend/src/components/graphs/ECharts-Detail.vue
frontend/src/components/graphs/ECharts-DetailGraph.vue
frontend/src/views/RepoDetail.vue
frontend/src/vue-echarts.d.ts
frontend/vue.config.js
frontend/yarn.lock

enable switching between the different graph flavours: d3, eChats and dygraphs (via button, as per now not dynamically)

Parallel graphs

---

frontend/src/components/repodetail/RepoBaseInformation.vue
frontend/src/components/repodetail/RepoCommitOverview.vue

Putting the repo detail view on a diet

Frontend makeover

---

frontend/src/components/graphs/ECharts-Detail.vue

The datapoint dialog is now shown when *right* clicking a datapoint. *Left* clicking opens the commit and CTRL+Left Click opens it in a new tab.

Only show ECharts config menu on right click

---

frontend/src/components/NavigationBar.vue
frontend/src/views/RepoDetailFrame.vue

- select that repo in detail view automatically
- hide comparison graph

[frontend] optimize for single repo use

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/storage/db/DatabaseStorage.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/storage/db/ThreadSafeConnectionProvider.java

This should resolve any weird auto commit related exceptions when two transactions are happening at the same time.

Use thread safe connection provider for jooq

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/ArchiveAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/archives/BenchRepoArchive.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/archives/RepoArchiveManager.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/archives/TarArchiveManager.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/exceptions/PrepareTransferException.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/util/TransferUtils.java

This pull request achieves the following goals:
- Reducing the likelihood of archives having an invalid/broken state by immediately deleting the archives whenever something goes wrong
- Better recovery from broken archives because all archives are deleted when Velcom initially starts
- Reducing size and complexity of `ArchiveAccess` by moving functionality into seperate files
- Created `BenchRepoArchive` which simplifies interaction with the benchmark repo
- Created `RepoArchiveManager` which simplifies interaction with normal repo archives
- Created `TarArchiveManager` in preparation for the ability to archive tar files in the future
- Fixes a case where `InputStream`s that were used for bench repo tar transfer were not closed properly

Archive improvements

---

docs/public-api/public-api.v2.yaml

Yet another round of adjustments to the API specification.
After enough changes have accumulated (again), I'll open this PR for review.

Api spec changes

---

backend/backend/pom.xml
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/runner/pom.xml
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/RunnerMain.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/GitProperties.java

This lets the backend and runner access their commit hashes, compile times and some other build info.

Build with commit hash

---

backend/backend/src/main/resources/db/migration/V4__better_indices.sql

The new indices should speed up certain queries by orders of magnitude...

Add some indices

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/QueueEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/utils/ArgumentParseException.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/utils/EndpointUtils.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/exception/ArgumentParseExceptionMapper.java
docs/public-api/public-api.v2.yaml

- Fix 500 when requesting graph without any dimensions
- Fix 500 when trying to add non-existent commit to queue

Make backend more robust

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java

Apparently (for whatever reason) prometheus or micrometer can't handle meters with the same name but differing tags. With this change the name of a meter that tracks a cache will automatically be prepended with the name of the cache so that this collision problem no longer occurs.

Fix cache meter name collision

---

frontend/src/components/rundetail/CommitDetail.vue
frontend/src/store/modules/commitDetailComparisonStore.ts
frontend/src/store/modules/detailGraphStore.ts
frontend/src/views/RunCommitDetailView.vue

1. We no longer request a detail graph when no dimensions are selected
2. We now properly show a 404 in the commit/run detail
3. The repo information and commit message is now center-aligned on smaller screens

Minor frontend improvements

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/DimensionDifference.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/RunComparator.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/CompareEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/RecentRunsEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/RunEndpoint.java
frontend/src/components/overviews/MultipleRunOverview.vue
frontend/src/store/types.ts

This PR re-implements significant runs for the `/recent/runs` endpoint and fixes related frontend bugs.

Significant recent runs

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/util/TransferUtils.java

Not doing that causes git to stop working :( Apparently an empty `.git/objects/info` and/or `.git/refs` folder is a requirement.

Preserve empty folders in TARs

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/BenchmarkReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/RepoReadAccess.java

This should cause Caffeine to report more stats to prometheus.

Improve cache stats with .recordStats()

---

.github/workflows/docker-publish.yml
docs/deploy.sh

This PR introduces our small trusty runner to github actions and automatically restarts it when things change :)

CD runner as well

---

frontend/src/router/index.ts

This PR will not change any frontend routes (as that might cause confusion with the repo-detail routes), but it will change the window title.

Rename Run-Detail to Detail

---

frontend/src/components/overviews/CommitOverviewBase.vue
frontend/src/components/overviews/RunOverview.vue

Previously runs linked to their commit, now they directly link to themselves.

Link runs to run not commit

---

frontend/src/components/CommitBenchmarkActions.vue
frontend/src/components/overviews/RunOverview.vue
frontend/src/components/repodetail/RepoCommitOverview.vue
frontend/src/components/rundetail/CommitDetail.vue

Adds links to bitbucket / github / gitlab in the commit actions

Link to commits on remotes

---

frontend/src/components/rundetail/MeasurementsDisplay.vue

This PR closes #127 and #115. See these issues for more details and comparison images.

Run detail table improvements

---

frontend/src/components/CommitChip.vue
frontend/src/util/ClipboardUtils.ts

Fix text copying in insecure contexts (e.g. over HTTP)

---

frontend/src/components/graphs/EchartsDetailGraph.vue
frontend/src/components/graphs/NewDytailGraph.vue

Sort the graph legend tooltips to match the displayed point order

---

frontend/src/App.vue
frontend/src/components/NavigationBar.vue
frontend/src/components/graphs/ComparisonGraph.vue
frontend/src/views/RepoComparison.vue

Navigate and refresh

---

frontend/package.json
frontend/src/App.vue
frontend/src/components/dialogs/DetailDatapointDialog.vue
frontend/src/components/graphs/DytailGraph.vue
frontend/src/components/graphs/EchartsDetailGraph.vue
frontend/yarn.lock

This PR is to tweak the fast detail graph and adding functionality that the former d3 graph had and the fancy detail graph already has

Graph enhancements

---

bench

The coverage is no longer rounded to the nearest percent.

Improve backend coverage metric parser

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/newaccess/repoaccess/RepoWriteAccess.java

Adding new repos was broken because I used jOOQ incorrectly, this PR fixes it again.

Fix adding new repo

---

backend/pom.xml
bench

Track checkstyle violations in the Aaaaaaaah-Instance to add some gamification (and get an overview).

Add a metric for checkstyle violations

---

backend/pom.xml
bench

This PR fixes some VelCom metrics and maybe adds some new ones.
- Exclude JOOQ from Checkstyle and code coverage
- Metric for SLOC (frontend and backend)
- Metric for TODO/FIXME count (frontend and backend)

Some metrics

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/QueueEndpoint.java
docs/public-api/public-api.v2.yaml
frontend/src/components/TaskRunnerOutput.vue
frontend/src/store/modules/queueStore.ts
frontend/src/util/TimeUtil.ts
frontend/src/views/TaskDetailView.vue

This patch shows the queue position and queuing times of tasks in the task detail view

Show queuing information in task detail

---

backend/runner/src/main/java/de/aaaaaaah/velcom/runner/Connection.java

The backend change revealed that the runner ws connection code was not as robust and bug-free as we thought...

Fix runner not being able to open ws connections after backend change

---

Dockerfile
Dockerfile-Single-Port

This patch adds some more comments and structure to the provided Dockerfiles.

Document dockerfiles

---

frontend/src/components/comparison/RunComparisonTable.vue
frontend/src/views/RunComparison.vue

Use dense table style for run comparison

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/archiveaccess/ArchiveReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/benchmarkaccess/BenchmarkReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/benchmarkaccess/BenchmarkWriteAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/benchmarkaccess/builder/NewRun.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/benchmarkaccess/entities/sources/TarSource.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/caches/LatestRunCache.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/caches/RunCache.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/dimensionaccess/entities/Interpretation.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/dimensionaccess/entities/Unit.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/repocomparison/TimesliceComparison.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/utils/EndpointUtils.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/state/AwaitAbortRunReply.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/state/TimeoutState.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/TestCommit.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/data/repocomparison/TimesliceComparisonTest.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/Connection.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/benchmarking/BenchResult.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/protocol/HeartbeatHandler.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/FileHelper.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/StringOutputStream.java
backend/shared/src/test/java/de/aaaaaaah/velcom/shared/protocol/statemachine/StateMachineTest.java

This PR must be merged after #217. Keeping it a draft until then.

Clean up some intellij warnings and checkstyle

---

backend/backend/src/test/java/de/aaaaaaah/velcom/backend/runner/DispatcherTest.java

Previously if the stars aligned just right, the background cleaner task could remove the runner after it was added but *before* the next line in the test, checking that the runner was added, was run.
This was possible as the runner *always* return an invalid ping time, even before it was added. This patch adjusts it to only return an invalid time once we verified the add was successful.

Try to make the cleansUpDisconnectedRunner test less flaky

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/dbupdate/DbUpdater.java

When repos are added, their main branch is now correctly tracked. The queue is no longer filled with old commits when tracked branches change.
This PR does *NOT* include a fix for the bug where untracking all branches and re-tracking a branch fills the queue with old commits.

Fix adding repos

---

frontend/src/components/graphs/graph/EchartsDetailGraph.vue

The default positioning system of echarts tried to place the tooltip completely inside the graph, which isn't a great idea with our tall and wide tooltips.
This patch implementes an adapted version of https://www.fabiofranchino.com/blog/efficient-tooltip-positioning-in-d3js-chart/
For more details, follow that link and look at the comments in this patch.
Closes: #263 (hopefully)

Implement our own tooltip position logic for echarts

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/benchmarkaccess/entities/MeasurementValues.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/recentruns/SignificantRun.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/recentruns/SignificantRunsCollector.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/RunComparator.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/significance/SignificanceDetector.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/significance/SignificanceFactors.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/significance/SignificanceReasons.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/Listener.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/github/GithubPrInteractor.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/CompareEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/RecentRunsEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/RunEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/utils/EndpointUtils.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonMeasurement.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonResult.java
docs/public_api.yaml
frontend/src/components/comparison/RunComparisonTable.vue
frontend/src/components/overviews/MultipleRunOverview.vue
frontend/src/components/rundetail/RunInfo.vue
frontend/src/components/runs/RunSignificanceChips.vue
frontend/src/store/modules/commitDetailComparisonStore.ts
frontend/src/store/modules/newsStore.ts
frontend/src/store/types.ts
frontend/src/util/json/CommitComparisonJsonHelper.ts
frontend/src/util/json/NewJsonHelper.ts
frontend/src/views/RunCommitDetailView.vue
frontend/src/views/RunComparison.vue

More significance info in more places.

More significance info

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/github/GithubPrInteractor.java

GH reaction: use :rocket: instead of :+1:

---

.github/workflows/docker-publish.yml

The old VPS is only partially hosted by me and after a fruitful, eventful and loyal one or two years the other party no longer has a use for it.
Therefore it will sadly cross the rainbow bridge in the near future and I need to migrate our instance off of it. This PR makes the necessary CI changes to complete the migration and also switches it to the location-independent image as part of #300.

Switch to new aaaaaaah vps instance

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/committaccess/CommitReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/github/GithubPrInteractor.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/access/committaccess/CommitReadAccessTest.java

This PR implements the second suggested solution from #315.
Closes #315.

Improve github bot messages

---

frontend/src/components/graphs/detail/MatrixDimensionSelection.vue
frontend/src/components/repodetail/GraphDimensionSelector.vue

The lean speedcenter detail page (https://speedcenter.informatik.kit.edu/velcom/repo-detail/) does not load, at all.
- The matrix selector did not care much for caching its lookups and performed a list lookup for every single cell in the table. This does not scale well.
- Webbrowser are not great at rendering hundreds of thousands cells in a table, especially if each cell is a Vue component.
Speed up the matrix selector, but also disable it altogether if too many cells would be shown. Its usefulness does heavily degrade if you need to scroll right 20 thousand times to see your metrics.
Bikeshedding for the limit is welcome, I chose it as a point that still renders basically instantly and does not cause major glitches on my laptop when scrolling.
The tree selector fares much, much better — …

Speed up matrix selector or disable it

---

shell.nix

A simple test PR to check whether CI is still working.

Remove nix shell
