leanprover/velcom

frontend/.env.development-remote
frontend/yarn.lock

Packages were updated via `yarn upgrade` to the latest version within their semver range. This should *theoretically* not introduce any breaking changes. A local build succeeded and seemed to be functional when trying it out in the browser.
I think this picture should be enough:
This hopefully also causes dependabot to retract its PRs.

[Frontend] Update dependencies

---

frontend/yarn.lock

This PR just bumps all dependencies to whatever newest version yarn deemed appropriate.
Steps to reproduce:
1. Delete `yarn.lock`
2. `yarn install`
3. `git shipIt`

Bump dependencies

---

.github/workflows/docker-publish.yml
docs/deploy-kit.sh

The runner.jar is only available as an artifact, not as a package. To be able to find that, the deployer needs to know the Github CI run ID.

Runner deployment

---

frontend/src/views/RepoDetail.vue

The toggle button group on the repo detail page was not in sync with the actual value upon first page load.
I don't really have any idea why the current solution doesn't work.
Use the provided `value` property of the button group and offload the checking to Vuetify, which seems to do it correctly in all cases.

Use proper v-btn-toggle API to mark selection

---

frontend/src/App.vue
frontend/src/axios-config-userdata.d.ts
frontend/src/components/Snackbar.vue
frontend/src/components/overviews/QueueOverview.vue
frontend/src/main.ts
frontend/src/store/modules/queueStore.ts
frontend/src/store/modules/repoStore.ts

The snackbar messages, while useful for debugging, were a bit annoying and probably the feature causing most complaints...
1. Success messages are *never* automatically displayed -- users likely only care about errors or slow loading pages
2. The "loading" indicator is only shown when the requests takes longer than one second (this time is up for debate)
3. Some actions - like (Re)benchmark or "One Up" - always show a success message, as their success has no other visual indication in the UI
4. The "All repo" request does not show any indicator (except for errors) as it might be triggered quite frequently and *should* be fast
#19

Subtile snackbar messages

---

frontend/.env.production
frontend/.env.production-kit-single-port
frontend/.env.production-single-port
frontend/vue.config.js

The router uses history mode and therefore needs to painfully aware of where the SPA is served from. In a previous commit support for deployment at a subpath was introduced, but the BASE_URL parameter in the router was missed.
This commit removes the "SITE" parameter introduced earlier and replaces it with BASE_URL. This ensures the router is kept in  sync with the publicPath.
Documentation for that should be added to the installation instructions.
Closes #31

[frontend] Fix public path settings

---

frontend/src/components/graphs/ECharts-Detail.vue

This PR will adjust the ECharts detail graph to take up 80% ov the viewport height, though that number might be adjusted.
It also removes the title, centers the toolbox and trims down the margins around the ECharts detail graph.
<hr>
<hr>
<hr>
<hr>

Resize the detail echarts chart to take up ~80% of the viewport height

---

frontend/src/components/graphs/ECharts-Detail.vue
frontend/src/views/RepoDetail.vue

1. Be on the ECharts graph
2. Have few enough commits to see the DAG
3. Switch to Dygraphs
4. Change the amount to 1000 or sth
5. Go back
This was fixed by not keeping the components alive and instead recreating them, when the graph type is switched. That way echarts will receive the mounted hook and update properly.
The graph did not reconsider its type when more data became available.
Now it checks the amount of points in its zoom area when the amount of displayed data changes.

Correct Echarts dag type on switch

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/BenchmarkReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/BenchmarkWriteAccess.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/access/BenchmarkAccessTest.java

Since getting the available measurements of a single repository takes way too long (about 350 milliseconds), measurement names are now cached in memory. This reduces the response time for `/all-repos/` to around 5 milliseconds while sacrificing almost no memory, since the amount of repositories and measurement names stored is probably quite low.
Additionally, every time we access any of the caches in BenchmarkReadAccess, we first check if we cache any data of repos that don't exist anymore and remove it.

Cache available measurement names for all repos

---

frontend/yarn.lock

[lodash had a prototype pollution vulnerability](https://www.npmjs.com/advisories/1523) (that VelCom shouldn't trigger in any case). This PR updates lodash (and a few other dependencies) to fix that vulnerability.

[frontend] Update yarn packages to fix lodash prototype pollution

---

frontend/src/views/RepoComparison.vue
frontend/src/views/RepoDetail.vue

In a previous patch vue-router was instructed to set the correct baseurl. Sadly that URL is not returned in the "path" property (which
returns the full path of the current route) and needs to be spliced together manually.
Finally closes: #31

Respect site-url on manually updated pages

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/DimensionDifference.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonDimensionDifference.java
backend/backend/src/main/resources/example_config.yml
docs/public-api/public-api.v2.yaml

- Change spec so `/test-token` returns a 204 No Content on success
- Rename the `absdiff`parameter to `diff` because `absdiff` sounds too much like `|a - b|`
- Change the `reldiff` formula from `newValue / oldValue` to `(newValue - oldValue) / oldValue` (see also [wikipedia](https://en.wikipedia.org/wiki/Relative_change_and_difference))

Fix api inconsistencies

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/DebugEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/KnownRunner.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/TeleRunner.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/states/RunnerState.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/protocol/serialization/serverbound/GetStatusReply.java
backend/shared/src/test/java/de/aaaaaaah/velcom/shared/protocol/serialization/serverbound/GetStatusReplyTest.java

This PR includes a `/debug` endpoint that is deliberately not listed in the API spec and may be changed at any time. It currently outputs the backend's and all runners' build time hashes.

Debug endpoint

---

backend/runner/src/main/java/de/aaaaaaah/velcom/runner/benchmarking/Benchmarker.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/systeminfo/CpuInfo.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/systeminfo/MemoryInfo.java

This PR changes the runner info and status a bit.
- CPU info includes thread count
- Memory info uses `MemAvailable` instead of `MemFree` and also doesn't call `MemFree` `used`.
- Version hash is included if a run fails

Better runner info

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/Listener.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/RepoEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/storage/repo/GuickCloning.java

This PR fixes the issue that old branches were still displayed even though they were deleted in the source repo. It also fixes the occasional Listener exception when trying to update commits for a repo.

Manage branches in Listener

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/CommitReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/CommitEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonCommit.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonCommitTest.java
docs/public-api/public-api.v2.yaml
frontend/src/components/rundetail/CommitDetail.vue
frontend/src/components/rundetail/CommitNavigationButton.vue
frontend/src/store/types.ts
frontend/src/util/CommitComparisonJsonHelper.ts

This PR stops `Merge ... into ...` commits (which are presumably automatically generated by github) from appearing as children of a commit.
I'm not sure if we should limit children to commits reachable from tracked branches or instead commits reachable from any branch (but not any ref).

Limit children to commits reachable from tracked branches

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/ArchiveAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/exceptions/MalformedRepoException.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/Listener.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/storage/repo/GuickCloning.java

When the bench repo changes its default branch, the backend now doesn't throw NPEs but instead tries to re-clone the bench repo. If the re-clone doesn't work, the backend doesn't start at all.

Don't crash when bench repo changes its default branch

---

frontend/src/components/rundetail/MeasurementsDisplay.vue
frontend/src/store/modules/commitDetailComparisonStore.ts
frontend/src/store/types.ts

Differences are not included if there was no unambiguous parent commit. In those cases the frontend shouldn't crash, it should just not display them.

Allow runs without differences

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/Dispatcher.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/ServerMasterWebsocketServlet.java

If a runner connects, the backend will ask the runner about its status.
Currently this is done using the normal periodic status requesting. This might cause the runner to ask for work before it has sent its information over. As a result the backend has an incomplete view of the runner and the backend-part of the runner dies.
There are two possible ways to fix this, that could also be combined:
1. Do not send any work over when the backend isn't sure it has all information. This is the approach implemented in this PR.
2. Directly request the status once a runner connected and hope the runner is nice and doesn't ask for work before answering

Do not send work to runners if backend is not ready

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/ArchiveAccess.java

Not deleting the archive of a repo after its transfer to a runner
causes the archive to exist forever in the archive directory
even though it probably is no longer needed.

Fix repo archive not being removed after transfer

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/Listener.java

Before this change, only commits reachable from tracked branches were marked as known (if the repo already had some known commits). Commits from untracked branches were completely ignored.
This caused an exception when a untracked branch is changed to tracked and a commit of this branch is inserted into the queue before the Listener had the chance to mark this commit as known.
This PR changes the Listener behaviour in such a way that now all commits (regardless if from a tracked or untracked branch) are at least marked as known. Only commits from tracked branches are then also inserted into the queue.

Always find all commits in Listener#checkForUnknownCommits()

---

frontend/Makefile

This change should make the makefile work on more systems than before. For
example on ubuntu, the package for yarn only contains an executable called
yarnpkg.

Use yarnpkg instead of yarn

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/CommitReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/RepoWriteAccess.java

This PR catches a few cases where a NoSuchRepositoryException was not dealt with properly, such as when requesting a `/commit` with an invalid repoid (that is still a valid UUID).

Fix 500 in some cases

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/repocomparison/RepoComparisonGraph.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/repocomparison/RepoDataResult.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/repocomparison/TimesliceComparison.java

This fixes two problems:
1.) Before this change, RepoComparisonGraph instances require a not-null startTime and endTime being passed to them via constructor.
Since there are circumstances (eg. when no data is available and no startTime, endTime were specified) where either startTime or endTime or both are null, this requirement cannot always be satisfied.
2.) When startTime or endTime are not specified and at least one commit is found, startTime and endTime were updated, but not passed to the resulting RepoComparisonGraph instance.

Fix startTime and endTime in RepoComparisonGraph

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/entities/Run.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/entities/sources/CommitSource.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/recentruns/SignificantRun.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/recentruns/SignificantRunsCollector.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/DimensionDifference.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/RunComparator.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/RecentRunsEndpoint.java

This pull requests changes the following two things:
1. The collection of recent significant runs is extracted into its own class on the data layer: `SignificantRunsCollector`
2. Performance is (hopefully) improved by batch loading commit data and parent runs per repo (instead of per run)

Improve performance of /recent/runs endpoint

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/BenchmarkReadAccess.java

Putting a null where it's not expected is usually not a good idea.

Clean up and fix potential bug

---

frontend/src/components/graphs/DimensionSelection.vue
frontend/src/components/graphs/MatrixDimensionSelection.vue

Previously not all selectors on the detail sorted their metrics and dimensions by name - now they do.

Sort metrics and benchmarks in the dimension selectors

---

frontend/src/views/RunCommitDetailView.vue

Bring the old "no run found" message, which explains how to benchmark a commit, back.

Add a small "No benchmark" message on run detail page

---

frontend/src/components/comparison/RunComparisonTable.vue
frontend/src/components/overviews/CommitOverviewBase.vue
frontend/src/components/rundetail/CommitDetail.vue
frontend/src/components/rundetail/RunDetail.vue
frontend/src/components/rundetail/RunInfo.vue
frontend/src/views/RunCommitDetailView.vue
frontend/src/views/RunComparison.vue

Previously the run comparison duplicated dimensions resulting in an *interesting* table. This PR fixes that.
It also adds the run information to the comparison page - but the commit information would probably be more useful? Some input is needed here.
The alignment of the infos is also a bit unpleasant. Sizing them dynamically helps on the detail page, but hurts us here. Maybe it should be scrapped and only commit info shown?

Fix run-comparison metrics and show Information

---

frontend/src/components/CommitChip.vue
frontend/src/store/modules/detailGraphStore.ts
frontend/src/util/ClipboardUtils.ts
frontend/src/util/TimeUtil.ts
frontend/src/views/NewRepoDetail.vue
frontend/src/views/RepoDetailFrame.vue
frontend/src/views/ShareGraphLinkDialog.vue

This PR depends on #87. That PR needs to be merged before this one!
This PR adds permanent links to the detail graph as well as a mechanism to generate them. If there is no X/Y zoom because the graph was not zoomed in, those checkboxes will be unselectable and turn into an "indeterminate" state.
Leading to this dialog:

Permanent links to detail graph

---

backend/backend/src/main/resources/db/migration/V2__runner_protocol_rewrite.sql

Previously, the random UUID generation used nested SELECTs, which sqlite
apparently just executed once. This meant that all tasks had the same UUID as
primary key, which obviously doesn't work.
This commit fixes the UUID deduplication by not using any SELECTs and instead
creating the UUID directly. This solution is a bit more verbose, but it works.

Fix db migrations

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/Listener.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/RepoEndpoint.java

This PR reverts a change that was made to fix an older issue, but created this new issue. It also fixes the other issue in a different way. A disadvantage of this new approach is that commits from untracked branches can no longer be added to the queue. This should be fixed in a future PR.
The "older issue" was that trying to add commits from a previously untracked branch to the queue immediately after tracking the branch failed because the listener had not yet added them to the known_commits table.

Fix listener not adding some commits to queue

---

frontend/src/store/index.ts
frontend/src/store/persistence.ts

Data in local/session storage might persist across multiple VelCom versions - even if they alter the storage format!
Previously VelCom might crash if that happens. This patch introduces a mechanism to automatically delete old stored data if we make any incompatible changes.

Delete outdated local storage

---

frontend/src/components/graphs/EchartsDetailGraph.vue
frontend/src/views/NewRepoDetail.vue

While resolving merge conflicts after the PRs I accidentally re-introduced a temporary "Permanent Link"-Button.
This PR deletes it again and also makes the layout of the share button a bit more compact.

Delete erroneous button, move share graph button up

---

Makefile

The docker image properly carries on without the agent present (that I made sure), but the Makefile target used for the *Github* CI doesn't. The aspect j weaver agent is optional: If it is present, detailed performance metrics for many parts of the system will be recorded and exposed in /prometheusMetrics.
That change should also be fast-forwarded to stable. It hopefully doesn't impact the quite large last PR, as that requires manual intervention in either case, but could be a nice test for the CI pipeline afterwards.
@Kha

Don't fail on aspectj weaver jar in Makefile

---

.github/workflows/docker-publish.yml

The previous CI pipeline takes around 10 minutes to fully deploy and 6 minutes to just build and test it. Crucially, building the backend and the two frontends does not depend on each other. So now Github Actions can launch those three tasks in parallel, and then build the docker images sequentially after all three have finished.
This cuts the pure build time in half and probably shaves off around 3 minutes of the full pipeline as well.

Parallelize CI

---

frontend/package.json
frontend/src/components/graphs/EchartsDetailGraph.vue
frontend/src/components/graphs/NewDytailGraph.vue
frontend/src/plugins/vuetify.ts
frontend/yarn.lock

This PR fixes theming issues with the new detail graphs in dark mode.
Before
After
Before
After-ish

Fully support dark mode in graphs

---

frontend/src/components/graphs/EchartsDetailGraph.vue
frontend/src/views/NewRepoDetail.vue

This PR is based on #113. It must be rebased and adjusted once that is merged. Only after that it can be merged.
This PR is also not required or *maybe* even wanted for the upcoming merge with stable.
Using the author-time based layout, commits tend to cluster in small groups (if you have a working sleep rhythm and are working from one timezone). This can make it hard to see what changes a commit introduced, as you need to zoom in extremely far, losing track of the greater trends.
To combat this, this PR introduces day-equidistant layouting. Every commit is placed in a bucket based on *the day of* its author date and then each bucket has an equidistant layout. Gaps still appear as they did before, but if multiple commits are made in a day they are layed out equidistantly with the gap …

[Experimental] Day equidistant echarts

---

backend/runner/src/main/java/de/aaaaaaah/velcom/runner/benchmarking/output/BenchmarkScriptOutputParser.java
backend/runner/src/test/java/de/aaaaaaah/velcom/runner/benchmarking/output/BenchmarkScriptOutputParserTest.java
backend/runner/src/test/resources/benchmark-script/valid-input.csv

Neither the previous nor this new behaviour is explicitly specified in the wiki. This change makes sense in the case of auto-discovered metrics. See [this run](http://speedcenter.informatik.kit.edu/velcom/run-detail/bab50d33-13a1-40c4-85a0-fda5f93f8b22/943687ad0977f11809ae80353d67e11cc0c2a02f) for an example.

Allow benchmarks without metrics

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/QueueEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/KnownRunner.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/TeleRunner.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/TeleBackend.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/benchmarking/Benchmarker.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/states/RunnerState.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/protocol/serialization/serverbound/GetStatusReply.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/LinesWithOffset.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/StringOutputStream.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/execution/ProgramExecutor.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/execution/StreamsProcessOutput.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/execution/WaitingFutureTask.java
backend/shared/src/test/java/de/aaaaaaah/velcom/shared/protocol/serialization/serverbound/GetStatusReplyTest.java
backend/shared/src/test/java/de/aaaaaaah/velcom/shared/util/execution/ProgramExecutorTest.java
bench
docs/public-api/public-api.v2.yaml
frontend/src/components/TaskRunnerOutput.vue
frontend/src/components/overviews/QueueOverview.vue
frontend/src/components/rundetail/RunDetail.vue
frontend/src/router/index.ts
frontend/src/store/modules/queueStore.ts
frontend/src/store/types.ts
frontend/src/util/QueueJsonHelper.ts
frontend/src/views/Queue.vue
frontend/src/views/TaskDetailView.vue

I would like to merge this after the other small to frontend changes are merged in master, as this change is slightly more likely to introduce problems and hasn't been tested on the live instance yet.
This patch allows the runner to capture the standard error stream of the executed program, send the last 100 lines to the backend and finally display it on the frontend in a new and shiney `task-detail` page you get to by clicking on queue items.
Closes #18 (hopefully)

Stream and display stdout/stderr in Runner

---

frontend/src/components/rundetail/MeasurementsDisplay.vue

Before this patch, clicking on an error button takes you to detail page (i.e. it executes the normal row click listener). This PR stops that.

Fix click on error button taking you to detail graph

---

frontend/src/views/NewRepoDetail.vue

This should hopefully finish addressing #133 for now.
Previous PRs selected the dygraphs graph ealier and alleviated some inefficiencies.
This PR now bases the decision on the *total* number of points instead of the *visible* number of datapoints, as Echarts still struggles with the sheer amount of points on small zoom levels.

Use dygraphs graph for large datasets

---

backend/Makefile
frontend/Makefile
frontend/package.json
frontend/src/ansi-to-html.d.ts
frontend/src/components/TaskRunnerOutput.vue
frontend/src/components/rundetail/MeasurementsDisplay.vue
frontend/src/components/rundetail/RunDetail.vue
frontend/src/util/TextUtils.ts
frontend/yarn.lock

This patch is *really* vain but it didn't take too long and helps parse dense log lines when the benchmark script crashes and burns or you are anxiously following the live build log.
This patch introduces support for ANSI colors in all places benchmark script output is shown:
- The popups triggered by the `error` buttons in the Run-Detail-View dialog
- The `Velcom / Benchmark script error` card in the same page
- The task-detail showing the last 100 lines the benchmark script reported so far
ANSI colors are converted using `ansi-to-html` and the resulting HTML is set with the vue equivalent of `innerHTML`. This introduces a trivial XSS vector which a malicious benchmark script could easily exploit. To prevent this, all ANSI escaping is done through a central `safeConvertAnsi` function …

Process and display ANSI colors

---

frontend/src/components/graphs/EchartsDetailGraph.vue
frontend/src/components/graphs/NewDytailGraph.vue
frontend/src/store/modules/detailGraphStore.ts
frontend/src/util/TextUtils.ts

This PR closes #149 and also fixes an XSS vulnerability in the graph tooltip code.
Dygraph already escapes label names on its own, so those dimensions will look a bit broken when you insert HTML tags.

Fix graph permanent link and graph tooltip xss

---

frontend/src/components/graphs/DimensionSelection.vue
frontend/src/components/graphs/EchartsDetailGraph.vue
frontend/src/components/graphs/GraphPlaceholder.vue
frontend/src/components/rundetail/MeasurementsDisplay.vue
frontend/src/store/modules/detailGraphStore.ts
frontend/src/views/NewRepoDetail.vue
frontend/src/views/Queue.vue

This PR aggregates a few fixes for bugs in #152 and should be able to be merged ~~at any time, when it feels big enough.~~
- Clicking into the duration field and letting it lose focus increments the days fetched by one (or breaks it in other ways)
- Fix spelling of `equidistant`
- Disable "Deselect all metrics if you have none selected"
- The graph placeholder does not have the correct size, so the UI jumps around when updating the graph
- Correctly display Refetch and Cancel all Tasks buttons in the queue when logging in / out
- Include "Day-Equidistant" setting in the permanent link
- Reference marker and compare line do not adjust to day-equidistant mode
- Error button text in Run-Detail is cut off after shrinking the table

Fix some small bugs

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/newaccess/committaccess/CommitReadAccess.java

Before this patch, `getTrackedCommitsBetween` ignored the `tracked` status of commits and returned *all* commits in the given date range.

Respect `tracked` in `getTrackedCommitsBetween`

---

frontend/src/views/NewRepoDetail.vue

Hitting "ENTER" in the duration field reloaded the page, as it submitted the form. This patch prevents the default browser action and calls `saveDuration` instead.

Fix "ENTER" in duration field

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/newaccess/committaccess/CommitReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/GraphDetailEndpoint.java
docs/public-api/public-api.v2.yaml
frontend/src/components/dialogs/DetailDatapointDialog.vue
frontend/src/components/graphs/Dygraph-Detail.vue
frontend/src/components/graphs/EchartsDetailGraph.vue
frontend/src/components/graphs/NewDytailGraph.vue
frontend/src/components/repodetail/RepoCommitOverview.vue
frontend/src/store/modules/detailGraphStore.ts
frontend/src/store/types.ts
frontend/src/util/GraphJsonHelper.ts
frontend/src/util/StorePersistenceUtilities.ts
frontend/src/views/NewRepoDetail.vue

Previously the detail graph was based on the author date (maybe to prevent rebases from being as annoying). With the introduction of the Day-Equidistant graph, rebases can actually be displayed in a quite alright-ish manner, even when sorting by committer date.
This makes the detail graph's arrows and layout a bit less confusing in projects where commits are authored long before they are rebased into the main branch(es).
Teach the Dytail Graph what "Day-Equidistant" means.
Closes #151

Commiter date based detail graph

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/QueueEndpoint.java
docs/public-api/public-api.v2.yaml
frontend/src/store/modules/queueStore.ts
frontend/src/views/Queue.vue

Before this patch the "Empty Queue" functionality was implemented in the frontend by making one HTTP request per task.
Now a proper endpoint was added that deletes all commits in the database in one go.

Empty queue using a dedicated endpoint

---

docs/nginx.conf

The default nginx request payload (1MB) is too small to fit any proper tar.

Allow up to 2GB in POST request payloads (TAR upload)

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/DimensionDifference.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/RunComparator.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonDimensionDifference.java
docs/public-api/public-api.v2.yaml
frontend/src/components/overviews/MultipleRunOverview.vue
frontend/src/store/types.ts
frontend/src/util/CommitComparisonJsonHelper.ts

For significant runs we display small chips with the significant metrics -- but if a run has more than one parent you might see the same dimension and metric with *two* different values. This commits links each chip to a run comparison with the relevant parent, so you can click on them and see where they belong to.

Link chips on home page to relevant run comparison

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/newaccess/committaccess/CommitReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/QueueEndpoint.java
docs/public-api/public-api.v2.yaml
frontend/src/components/CommitBenchmarkActions.vue
frontend/src/store/modules/queueStore.ts

Previous patches disabled the one-up endpoint as backend support was dropped -- this patch enables it again.

Re-add "One up" endpoint

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/queue/Queue.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/newaccess/taskaccess/TaskWriteAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/QueueEndpoint.java
docs/public-api/public-api.v2.yaml
frontend/src/components/FileSelectComponent.vue

This PR adds support for `tar.gz` files, iff the user actually ends the file name with `.tar.gz` as no magic probing is done.
Files are uncompressed on-the-fly and then written to disk, so the storage benefits only apply to the in-flight request.
TODO:
Closes: #189

Support uploading of gzipped tars

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/entities/MeasurementValues.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/DimensionDifference.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/RunComparator.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/CompareEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/RunEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/utils/EndpointUtils.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonDimensionDifference.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonMeasurement.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonResult.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonMeasurementTest.java
docs/public-api/public-api.v2.yaml
frontend/src/components/overviews/MultipleRunOverview.vue
frontend/src/components/rundetail/MeasurementsDisplay.vue
frontend/src/store/types.ts
frontend/src/util/CommitComparisonJsonHelper.ts

This PR moves the `stddev` and `stddevPercent` fields from ´DimensionDifference` to `Measurement` as they are also useful without a diff to the parent run.

Stddev without differences

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/Delays.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/PeriodicStatusRequester.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/runner/single/PeriodicStatusRequesterTest.java

Fixes a bug introduced in e3f5905e8270305a7240a3072201f7f55cc7fb5a causing the backend to not sleep *at all* if the runner had no result. If it had one it slept for a very, very short duration due to a unit mismatch. This leads to a lot of useless log output and CPU usage in the runner and backend.

Sleep for 5 seconds between "get_status" requests

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/TeleRunner.java

When a runner stays disconnected for long enough (more than the gracePeriod + some leeway) the corresponding TeleRunner will get cleaned up. While doing so, the dispatcher checks if the runner has really disconnected and if so *disposes* it. This patch makes the `dispose` method abort any task the TeleRunner might still cling onto, so another runner can later take over and finish what the first one failed to complete.

Reschedule commits on another runner when one leaves

---

backend/runner/src/main/java/de/aaaaaaah/velcom/runner/Connection.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/TeleBackend.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/benchmarking/Benchmarker.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/states/AwaitingBench.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/states/AwaitingRequestRunReply.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/states/AwaitingRun.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/states/RunnerState.java
backend/runner/src/main/resources/logback.xml
backend/runner/src/test/java/de/aaaaaaah/velcom/runner/benchmarking/BenchmarkerTest.java

The runner's default log level is now INFO. Cleaned up the log messages a bit to make them more consistent and show a bit more info.

Make runner log messages less verbose

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/recentruns/SignificantRunsCollector.java

Now, partially successful runs where only insignificant dimensions failed are no longer significant. However, the list of significant runs is still often full of failed or partially failed runs, which can be annoying. Possible solutions would be:
1. Only successful runs can be significant
2. Partly failed runs (yellow) are treated like successful runs (i. e. the failed dimensions are ignored). Completely failed runs are still automatically significant.
I'm not sure whether this is really an issue that needs to be solved, or whether it's fine as is. Any opinions, @Kha?

Change significance criteria

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/BenchmarkReadAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/newaccess/AccessUtils.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/newaccess/benchmarkaccess/entities/TarSource.java

Fixes a bug where the run detail endpoint would incorrectly return tar sources without repo id even though the tars were attached to a repo.

Fix run detail endpoint by returning repo id for tars attached to repos

---

frontend/src/components/comparison/ComparisonRunInfo.vue
frontend/src/components/overviews/TarOverview.vue
frontend/src/views/RunCommitDetailView.vue
frontend/src/views/RunComparison.vue
frontend/src/views/TaskDetailView.vue

This commits shows the tar information in the run detail or run comparison views:

Display tar sources in run detail / comparison

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/recentruns/SignificantRunsCollector.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/runcomparison/DimensionDifference.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/RunEndpoint.java
docs/public-api/public-api.v2.yaml
frontend/src/components/RunSignificanceChips.vue
frontend/src/components/overviews/MultipleRunOverview.vue
frontend/src/components/rundetail/CommitDetail.vue
frontend/src/store/modules/commitDetailComparisonStore.ts
frontend/src/store/types.ts
frontend/src/views/RunCommitDetailView.vue

Show the significant dimension chips visible on the home page also on the run detail page.

Show significance chips in the run detail view

---

frontend/src/axios-config-userdata.d.ts
frontend/src/components/Snackbar.vue
frontend/src/components/rundetail/MeasurementsDisplay.vue
frontend/src/main.ts
frontend/src/store/modules/commitDetailComparisonStore.ts
frontend/src/store/modules/repoStore.ts
frontend/src/views/Queue.vue

This PR removes the colors from the stddev and stddev percent columns (and also fixes a deserialization bug with significant differences).
Additionally, the "loading" snackbar shown when re-fetching repos now stays up, even if other snackbar messages show up.
Closes #215

Remove stddev colors and other minor issues

---

frontend/src/components/graphs/DytailGraph.vue
frontend/src/components/graphs/MatrixDimensionSelection.vue
frontend/src/components/graphs/OverscrollToZoom.ts
frontend/src/store/modules/detailGraphStore.ts
frontend/src/views/RepoDetail.vue

This PR changes a few things about both detail graph types. 
Most importantly, the graphs now only display whole days (midnight to midnight).  This also fixes #192 , because it prevents commits from being "cut off".
If VelCom would show an empty graph because no metrics are selected or there are no commits in the selected time span, it now shows a neat overlay instead, similar to the one on the comparison graph.

Minor graph alterations

---

frontend/src/App.vue
frontend/src/components/NavigationBar.vue

Clicking one of the navigation buttons should refresh the view.
Do not emit a refresh event when first *navigating* to the page, as that
is unnecessary: The page was just loaded, so it is "fresh".
To do this the navigation buttons emitted a "refresh" event when
clicked and then the route name was checked against the current route
name. If the names matched, the view was refreshed. If they differed we
detected a real navigation and suppressed the refetch.
The custom click handler is fired *after* the navigation was complete.
This means it will *always* see a matching route name, no matter whether
there actually was a navigation. This renders the whole check useless
and every page is refreshed twice.
We now watch for route changes. This watcher is triggered *before* the
click event. The …

Suppress double page refresh when using navigation buttons

---

frontend/src/scss/variables.scss

This might be a bit of a controversial change, but the xl breakpoint is now triggered at 1300 instead of 1900 pixels.
Due to this VelCom will now use nearly the full width of the window a lot earlier and not have as much space around it, even if you open it on a smaller monitor or split/resize the window.
If most feel this is a "Verschlimmbesserung", the PR can be closed.

Use "xl" breakpoint earlier

---

frontend/src/store/modules/detailGraphStore.ts

This ensures the display looks the same even if the day-equidistant graph moved some later commits to be barely visible on the right/left edge. Those commits would not be loaded without expanding the range as they do not belong into the displayed area, they were just moved by the day-equidistant setting.

Expand fetched date range in permalinks by a day

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/PeriodicStatusRequester.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/RunnerConnection.java

Previously the backend would print an exception with stacktrace saying it couldn't tell the runner to clear results. This isn't too surprising, as the runner *just disconnected*. This PR ignores exceptions arising when communicating with the runner, *if the connection was already closed*. Additionally it now logs runner disconnects on the `INFO` level.

Ignore exceptions from closed runners, log runner disconnects

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/QueueEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/Dispatcher.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/IDispatcher.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/KnownRunner.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/TeleRunner.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/runner/DispatcherTest.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/runner/single/TeleRunnerTest.java
frontend/src/views/TaskDetailView.vue

The runner output on the task detail page is no longer cleared. Additionally, the backend now keeps track of the last two tasks per runner and allows fetching their last lines after they have finished.

Persist task output in task detail view

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/CommitEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonCommit.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonCommitTest.java
docs/public-api/public-api.v2.yaml
frontend/src/components/rundetail/CommitDetail.vue
frontend/src/store/types.ts
frontend/src/util/CommitComparisonJsonHelper.ts

This PR extends the API for the `/commit` endpoint to include the information whether the commit is tracked and which of its parents are tracked. This is a breaking change, so the backend and frontend should both be updated in this PR.
This PR must be merged after #217. Keeping it a draft until then.

Show whether a commit and its parents are tracked

---

scripts/docker/build-docker

The `build-docker` script had a wrong default value for the `metrics` argument, causing them to be *always* included.
@Kha Removing `--no-metrics` with this patch should work (better).
Feel free to apply the patch yourself and to close this PR.

Fix default value of "metrics" argument for "build-docker" script

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/benchmarkaccess/BenchmarkReadAccess.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/TestDb.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/access/benchmarkaccess/BenchmarkReadAccessTest.java

Recent runs are now ordered by their commit's committer date instead of the run's start time. This means that re-runs of a commit may no longer appear at the top of the list of significant runs.
Tar runs are not included in the recent runs any more.

Change order of recent runs

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/runner/single/state/TeleRunnerState.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/Connection.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/TeleBackend.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/states/RunnerState.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/protocol/serialization/serverbound/ServerBoundPacket.java
backend/shared/src/main/java/de/aaaaaaah/velcom/shared/protocol/serialization/serverbound/ServerBoundPacketType.java

The runner's connection to the backend is sometimes a little unstable. While the protocol is robust enough that this does not matter much, it would be nice if the runner simply stayed connected the entire time.
This PR adds logging for weird packets to help us get to the bottom of the connection instabilities.

More runner protocol logging

---

README.md
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/taskaccess/TaskWriteAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/taskaccess/exceptions/TaskCreationException.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/queue/Queue.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/QueueEndpoint.java

Tar files can be uploaded to the queue using only `tar` and `curl`. The server's output is just plain JSON describing the newly created task. This PR documents how to do this in the README.
I could add a separate endpoint that returns formatted text instead of JSON, but that's probably unnecessary.

Document how to upload tars with curl

---

backend/runner/src/main/java/de/aaaaaaah/velcom/runner/Connection.java
backend/runner/src/main/java/de/aaaaaaah/velcom/runner/TeleBackend.java

A bug report showed the runner leaking file descriptors when doing lots of
reconnection attempts.
Apparently, HttpClient only cleans itself up if there are no more references to
it. In practice, this means that it only cleans itself up once a few other
objects with references to it have been garbage collected. However, it can take
quite a while for this to happen "naturally".
For each HttpClient or associated WebSocket (I'm not sure which) a few file
descriptors are opened. These are not freed immediately after a connection
attempt fails, but instead only after GC (as described above). When testing with
a reconnection delay of 0.1 seconds, velcom at one point managed to hold over
9,000 file descriptors.
This commit "fixes" the issue by kicking off GC manually via System.gc()
whenever a …

Attempt to fix fd leak

---

backend/backend/src/main/resources/db/migration/V11__speed_up_repo_deletion.sql

By adding a few strategically placed indices, deleting a large repo now takes seconds rather than minutes.

Speed up repo deletion

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/dbupdate/DbUpdater.java
backend/backend/src/main/resources/db/migration/V12__commit_tracking_flags.sql
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/TestDb.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/access/benchmarkaccess/BenchmarkReadAccessTest.java
backend/backend/src/test/java/de/aaaaaaah/velcom/backend/access/committaccess/CommitReadAccessTest.java

Previously, velcom would add a lot of old commits to the queue when a branch is marked as tracked in a repo with no tracked branches. This PR should fix that issue.

Fix queue issues

---

frontend/src/components/CommitBenchmarkActions.vue
frontend/src/components/InlineMinimalRepoDisplay.vue
frontend/src/components/comparison/RunComparisonTable.vue
frontend/src/components/dialogs/RepoAddDialog.vue
frontend/src/components/dialogs/RepoUpdateDialog.vue
frontend/src/components/graphs/comparison/ComparisonGraph.vue
frontend/src/components/graphs/comparison/ComparisonGraphSettings.vue
frontend/src/components/overviews/MultipleRunOverview.vue
frontend/src/components/overviews/TarOverview.vue
frontend/src/components/repodetail/RepoBaseInformation.vue
frontend/src/components/repodetail/RepoGraph.vue
frontend/src/components/rundetail/CommitDetail.vue
frontend/src/components/search/SearchResultBranch.vue
frontend/src/components/search/SearchResultList.vue
frontend/src/router/index.ts
frontend/src/store/modules/comparisonGraphStore.ts
frontend/src/store/modules/detailGraphStore.ts
frontend/src/store/modules/repoStore.ts
frontend/src/store/types.ts
frontend/src/util/LinkUtils.ts
frontend/src/util/RepoJsonHelper.ts
frontend/src/util/StorePersistenceUtilities.ts
frontend/src/util/TimeUtil.ts
frontend/src/views/Home.vue
frontend/src/views/RepoComparison.vue
frontend/src/views/RepoDetailFrame.vue
frontend/src/views/RunCommitDetailView.vue
frontend/src/views/Search.vue
frontend/src/views/ShareGraphLinkDialog.vue

In the past weeks quite a few frontend changes have accumulated on this poor branch and it is quite clearly overripe.
- Fix a few edge cases with repo deletion invalidating the local storage state
- Show a proper 404 page if you navigate to a repo detail page where the correspondig repo doesn't exist
- Remove "View on git{hub, lab}" buttons if we can't parse a proper remote URL for a commit (e.g. for `file://` repos)
- Remove some unneeded padding here and there
- Remove the repo token from the add and update dialogs
- Change the home page to an infinite lazy list (Closes #247)
- Show the percentual difference in the run comparison (Closes #255)
- Add a compare button to TAR detail pages (Closes #254)
- Add a way to search for branches in Voogle
- Permanent links for the comparison graph

Various frontend fixes and enhancements

---

frontend/src/store/persistence.ts
frontend/src/store/types.ts
frontend/src/util/Serialisation.ts

The previous implementation relied on `constructor.name`, which is mangled by terser in production builds, completely breaking
deserialization.
Just using the minified names is also broken, as they might conflict.
This leaves us with two main options:
- Disable minification
- Somehow store the name in a way terser won't touch
This PR implements option two: The serialized name is explicitly stored in a static class property.

Fix frontend persistence in minified production builds

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/QueueEndpoint.java

One-ups usually add a lot of commits at once. If they're all set to manual priority, this means that newly detected commits from other repos are blocked until the one-ups finish. This is of course not ideal, especially when one-upping large amounts (e. g. thousands) of commits.
This PR changes the priority of one-upped commits to listener priority, meaning they'll be sorted into the round-robin schema.

Add one-ups with listener, not manual priority

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/repoaccess/entities/Repo.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/Listener.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/github/GithubApiError.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/listener/github/GithubPrInteractor.java
frontend/src/components/repodetail/GithubBotCommandChips.vue
frontend/src/components/repodetail/RepoBaseInformation.vue

Small fixes and adjustments for the GitHub bot

---

frontend/src/components/graphs/graph/EchartsDetailGraph.vue

After a dependency update, the arrow function `findFirstSuccessful` apparently bound to a different "this" - one *before* the component was properly initialized. This was bad, as it did not receive any reactive getters and was reading outdated values.
This PR converts it to a normal function, which properly captures the this context.

Fix detail graph loading

---

frontend/.eslintrc.js
frontend/src/components/graphs/graph/EchartsDetailGraph.vue
frontend/src/store/modules/detailGraphStore.ts
frontend/src/store/persistence.ts
frontend/yarn.lock

Small frontend fixes

---

frontend/src/components/graphs/helper/GraphTimespanControls.vue
frontend/src/store/modules/comparisonGraphStore.ts
frontend/src/store/modules/repoStore.ts
frontend/src/store/types.ts

The last dependency upgrades apparently subtly changed how `this` is bound in Vue components and this PR removes the (based on grep) last usage of arrow functions in instance fields.

Fix date selection dialogs in detail graph

---

frontend/src/components/graphs/statuscomparison/StatusComparisonGraph.vue
frontend/src/components/misc/RepoSelectionComponent.vue
frontend/src/views/StatusComparison.vue

See https://github.com/IPDSnelting/velcom/issues/264#issuecomment-877184030. This PR allows you to interact with the comparison graph while no baseline is selected. This might be helpful if you select actually comparable dimensions of similar magnitude.
https://user-images.githubusercontent.com/20284688/125109663-f060b600-e0e3-11eb-82f4-adc34f337992.mp4

Allow comparing repos in bar graph without selecting a baseline

---

frontend/src/components/graphs/helper/GraphTimespanControls.vue

Restricting the maximum time doesn't serve much purpose as "today" is clearly highlighted. Having this restriction makes it a bit harder to work around weird UI bugs, should they happen (like timezone offsets changing the allowed max date for a client...).
Also removes two watchers that shouldn't be needed anymore, as they refer to computed properties.

Remove "max" date restriction in time selector

---

.github/workflows/docker-publish.yml
scripts/deploy-aaaaaaah/deploy.sh

The runner CD was broken after I restructured my infrastructure. This PR removes the outdated deployment scripts.
Closes #290

Do not deploy the runner artifact in github actions

---

.github/workflows/docker-publish.yml

The workflow file used the wrong tag to update the location independent image, overwriting the "main" image instead (used by the Aaaaaaah instance). Apparently nothing broke which is nice, but this PR fixes the image version.
Closes #306

Fix publish workflow for location independent image

---

frontend/src/util/Texts.ts

Since version 5 of `ansi_up`, it now properly handles and enables HTML sanitization, which we also perform ourselfs. This results in double-escaping and output like "&lt;error&gt;" instead of "<error>".
This patch removes our own escaping and relies on `ansi_up` to do it properly. [Their changelog](https://github.com/drudru/ansi_up/releases/tag/v5.0.0) assures us that this should always:tm: be the case.  
Their escape handling seems a lot less robust than ours but we don't really have much choice and they seem to follow the OWASP guideline [here](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#rule-1-html-encode-before-inserting-untrusted-data-into-html-element-content) at least. For reference, this is what they do:
```ts
private …
```

Fix HTML double escaping in ANSI colored text

---

frontend/src/components/graphs/statuscomparison/StatusComparisonGraph.vue

This PR just sorts the dimensions in the status comparison graph alphabetically:

Sort series data in status graph alphabetically

---

docs/bench_repo_specification.md

As discovered in #302, the bench repo specification is a bit light on details about errors, not making a clear distinction between `bench` script panics and errors in the benchmarked program. Due to this is it wasn't always very clear why VelCom chose to present errors in a given way and interpreted/did not interpret the output as a json result.
This PR aims to clarify this in the specification.

Clarify errors in bench script specification

---

.github/workflows/docker-publish.yml

The deployment only needs to *ping* the server behind but that service isn't always *too* kind with what it returns. It drags out the response until it finished re-deploying all changed docker containers which might cause curl to time out. Additionally, as seen in the last run, it might re-deploy the *reverse proxy*, causing the response to get totally lost.
This isn't a problem though, the service will eventually update velcom even if it does not respond kindly.

Ignore curl's exit code in Aaaaaaah deployment

---

backend/backend/src/main/java/de/aaaaaaah/velcom/backend/ServerMain.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/dimensionaccess/DimensionWriteAccess.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/access/dimensionaccess/exceptions/NoSuchDimensionException.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/endpoints/DimensionsEndpoint.java
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/restapi/jsonobjects/JsonDimensionId.java
docs/public_api.yaml
frontend/src/store/modules/cleanupStore.ts

Currently deleting dimensions with a `/` in the benchmark or metric name does not work, as the nginx proxy in the docker image *unescapes them* before passing it on to the backend. This is not ideal, as the backend then interprets them as a normal path separator and fails to find a matching endpoint.
Rather than trying to get nginx to behave (which seems to be quite involved when applied in a proxy_pass directive) and forcing every user to configure their reverse proxy to preserve unencoded slashes, we just sidestep this by substituting `:s` for `/` and `:c` for `:`. This is quite easy to apply and reverse using `String::replace` and should not be reversed by any proxy layer.
As nginx seems to decode the url, there might be other parameters leading to incorrect interpretation in the …

Fix deletion of dimensions with `/` in the name

---

frontend/src/views/RunCommitDetailView.vue

[Vue (intelligently) reuses components when using v-if](https://v2.vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key). In this case, this lead to vue reusing the run-detail row for the commit component once the commit was fetched asynchronously.
This, in turn, triggered a re-render of the run-detail page -- including the relatively expensive measurement table -- into a new row.
Giving either the commit view (or tar) or the run-detail row a unique key prevents this reuse and only renders the table once. This patch adds keys to all rows for good measure, but the other components are relatively inexpensive to recreate and don't matter as much.
It is still a bit unfortunate, that the commit view jumps in afterwards and changes the layout. Its dimension (and whether it …

Only render run detail component once

---

frontend/src/components/rundetail/MeasurementsDisplay.vue

This reduces the measurement table rendering time by a bit for your 8000 metric usecase:
```
// before
items: 269ms - Timer beendet MeasurementsDisplay.vue:200
// after
items:  21ms - Timer beendet MeasurementsDisplay.vue:200
```
The remaining time is now mostly spent in the framework and rendering AFAICT, but I didn't look too closely.

Compute run detail difference table entries in linear time

---

frontend/src/components/comparison/RunComparisonTable.vue
frontend/src/store/types.ts
frontend/src/views/RunComparison.vue

@Garmelon showed me a link (http://speedcenter.informatik.kit.edu/mathlib4/compare/1ed91d01-45f4-45a2-9d05-996d09b28b72/to/b7d05b7c-6dd2-4386-abec-1c376f284bab) which took ~40 seconds to load, freezing the page in the process. This seemed a bit odd and maybe not fully desired…
Looking at some [firefox profiles](https://share.firefox.dev/45hOSU8), most of the rendering time was spent finding elements:
The flame graph spans around 40 seconds, with 36 seconds spent in rendering.
This is obviously not ideal and looking at the code, most of the corresponding lines are finding measurement results for a given dimension, because the table first builds a list of all dimensions and then compares them between both runs. This necessitates finding results for both runs given a dimension.
I now build …

Speed up comparison page

---

frontend/src/components/comparison/RunComparisonTable.vue
frontend/src/components/rundetail/MeasurementsDisplay.vue

Previously, as noted by @Garmelon, the tables for the run comparison and measurement showed 200 rows, but the row selection checkbox was stuck at 5:
The cause for this odd behaviour is that the available options do not include the new default set in a PR a while ago, disallowing it to be selected. An easy fix is to just set the possible options and include the default :)
Feel free to bikeshed the possible options.

Include default items per page setting in options

---

backend/backend/pom.xml
backend/backend/src/main/java/de/aaaaaaah/velcom/backend/data/significance/SignificanceDetector.java
backend/runner/pom.xml
frontend/src/components/comparison/RunComparisonTable.vue
frontend/src/components/rundetail/MeasurementsDisplay.vue
frontend/src/components/runs/RunSignificanceChips.vue

Format and signify mathlib instructions count by absolute value

---

.github/workflows/docker-publish.yml
scripts/docker/Dockerfile

The current image seems to be broken on my host after an update, due to https://bugs.openjdk.org/browse/JDK-8287073?focusedId=14497312&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14497312.
The correct fix would be to actually update dependencies, but I don't quite have the time for that at this instance.

[meta] Switch to more maintained java 11 docker image
